db-ui/elements

cypress/integration/elements/db-select.spec.js
packages/db-ui-elements-stencil/src/components/db-button/readme.md
packages/db-ui-elements-stencil/src/components/db-checkbox/readme.md
packages/db-ui-elements-stencil/src/components/db-icon/readme.md
packages/db-ui-elements-stencil/src/components/db-input/readme.md
packages/db-ui-elements-stencil/src/components/db-link/readme.md
packages/db-ui-elements-stencil/src/components/db-radio/readme.md
packages/db-ui-elements-stencil/src/components/db-select/stories/db-select.intro.stories.mdx

we need to figure out how to document the new way of styling correctly

refactor: hide obsolete style sections and unstyled variant

---

.storybook/dbTheme.js
.storybook/manager-head.html
.storybook/manager.js
.storybook/preview-head.html

Update storybook theming with db specific colors and styles

feat: storybook theming

---

.github/scripts/publish-npm.sh

fix: "next" tag nomenclature

---

.github/scripts/auto-update-pr.js
.github/workflows/99-auto-update-pr.yml
.github/workflows/auto-update.yml

feat: add auto update for v3 branch

---

.github/dependabot.yml

let's align the comment and configuration on lines 11 and 15:
https://github.com/db-ui/elements/blob/main/.github/dependabot.yml#L11L15

refactor: let's check for dependency updates on a daily basis

---

showcase/vue-showcase/vite.config.ts

Vite could resolve the path by itself from now on.

fix: issue with vite (vue-showcase)

---

.github/actions/cancel-workflow/action.yml
.github/workflows/00-init.yml
.github/workflows/default.yml
.github/workflows/pull-request-opened.yml
.github/workflows/pull-request.yml

We need to check for another [GitHub environment variable](https://docs.github.com/en/actions/learn-github-actions/environment-variables).

fix: pipeline

---

.github/actions/extract-branch/action.yml

adapted from https://github.com/db-ui/base/pull/112

fix: issue deployment for releases and tags

---

.storybook/main.js

Moved a comment due to new code to its corresponding code line and added a new one for clarity.

chore(docs): added and moved comments

---

README.md
packages/db-ui-elements-angular/README.md

Providing a temporary solution for Angular 14 problems when using `@db-ui/ngx-elements`.

docs(faq): angular problem

---

package-lock.json

The dependency `browserslist` needs to get update regularly.

refactor: updated browserslist

---

package-lock.json

Resolves https://github.com/db-ui/elements/issues/1346

refactor: updated browserslist dependency

---

packages/db-ui-elements-stencil/src/components/db-select/db-select.scss
packages/db-ui-elements-stencil/src/components/general.scss

Resolves https://github.com/db-ui/elements/issues/1406

fix(select): native inner element doesn't account Web Components width

---

packages/db-ui-elements-stencil/src/components/general.scss

Resolves https://github.com/db-ui/elements/issues/1426
Partly rolled back previous out of https://github.com/db-ui/elements/issues/1406

fix: input elements width collapsed #1426

---

packages/db-ui-elements-stencil/src/components/db-accordion/db-accordion.tsx
packages/db-ui-elements-stencil/src/components/db-accordion/readme.md
packages/db-ui-elements-stencil/src/components/db-accordion/stories/db-accordion.intro.stories.mdx

Resolves https://github.com/db-ui/elements/issues/1571

fix(accordion): added missing property

---

package-lock.json
packages/db-ui-elements-stencil/package.json

as suggested by changelog out of Stencil v3 update: https://github.com/ionic-team/stencil/blob/main/BREAKING_CHANGES.md#puppeteer-v10-required

refactor: added missing `devDependency`

---

.github/actions/download-tar-artifact/action.yml
.github/actions/extract-branch/action.yml
.github/workflows/01-build-showcases.yml
.github/workflows/01-build-stencil-targets.yml
.github/workflows/01-get-latest-tag.yml
.github/workflows/01-get-publish-version.yml
.github/workflows/03-deploy-gh-pages.yml
.github/workflows/03-publish-packages.yml

Resolves https://github.com/db-ui/elements/issues/1640

refactor: updated GH Actions commands

---

.husky/pre-commit
.lintstagedrc

Resolves https://github.com/db-ui/elements/issues/1656

refactor: consolidated pre-commit scripts #1656

---

e2e/cypress/e2e/03-0-action/db-toggle.cy.js
packages/db-ui-elements-stencil/src/components/db-toggle/db-toggle.tsx
packages/db-ui-elements-stencil/src/components/db-toggle/stories/db-toggle.intro.stories.mdx

Resolves https://github.com/db-ui/elements/issues/1799

fix(`toggle`): added missing `name` property

---

.vscode/extensions.json

refactor: added recommendation for `stylelint` VS Code extension

---

package-lock.json
packages/db-ui-elements-stencil/package.json
packages/db-ui-elements-stencil/src/components/db-input/__tests__/db-input.spec.tsx
packages/db-ui-elements-stencil/src/components/db-input/db-input.scss
packages/db-ui-elements-stencil/src/components/db-input/db-input.tsx
packages/db-ui-elements-stencil/src/components/db-input/stories/db-input.intro.stories.mdx
packages/db-ui-elements-stencil/src/components/db-textarea/db-textarea.scss
packages/db-ui-elements-stencil/src/components/db-textarea/db-textarea.tsx

Resolves https://github.com/db-ui/elements/issues/2499

feat(db-input): added counter

---

e2e/cypress/e2e/00-0-intro/welcome-story.cy.js
packages/db-ui-elements-stencil/src/stories/intro/getting-started.stories.mdx
packages/db-ui-elements-stencil/src/stories/intro/welcome.stories.mdx

fix: wrong links for getting started cards

---

showcase/react-showcase/vite.config.js
showcase/reactwind-showcase/vite.config.js

fix: issue with react-showcases wrong path

---

doc/howto-style.md
packages/storybook/.storybook/dbTheme.js

some of the URLs within our [Marketingportal](https://marketingportal.extranet.deutschebahn.com/marketingportal) documentation have changed due to the release of version 3 the latest.

docs(marketingportal): updated urls

---

packages/db-ui-elements-angular/package.json
packages/db-ui-elements-angular/projects/lib/package.json

Resolves https://github.com/db-ui/elements/issues/2606

fix: issue with angular lib having old version

---

doc/howto-angular.md

let's remove this obsolete character

fix(docs): removed obsolete tilde

---

packages/db-ui-elements-stencil/src/components/db-input/stories/db-input.intro.stories.mdx

the innerText & value example doesn't look that nice

docs(datalist): simplification

---

.github/workflows/99-self-healing-dependabot-updates.yml
.github/workflows/pull-request.yml

for prettier and stylelint updates

feat: self healing dependabot updates
